#!/bin/bash
# Build "paper-dive.app" — a Dock-launchable wrapper around the local server.
#
#   ./scripts/make_app.sh              -> ~/Applications/paper-dive.app
#   DEST=/Applications ./scripts/make_app.sh
#
# The app owns the server: launching it starts uvicorn and opens a window;
# closing the window (or quitting the app) shuts the server down again.

set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEST="${DEST:-$HOME/Applications}"
APP="$DEST/paper-dive.app"

if [ ! -x "$REPO/.venv/bin/python" ]; then
  echo "No virtualenv at $REPO/.venv — run:  uv venv && uv pip install -e ." >&2
  exit 1
fi

echo "Building $APP"
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

# ---------------------------------------------------------------------- icon

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT
python3 "$REPO/scripts/make_icon.py" "$work/icon.png"

mkdir -p "$work/paper-dive.iconset"
for size in 16 32 128 256 512; do
  sips -Z "$size" "$work/icon.png" --out "$work/paper-dive.iconset/icon_${size}x${size}.png" >/dev/null
  sips -Z "$((size * 2))" "$work/icon.png" \
    --out "$work/paper-dive.iconset/icon_${size}x${size}@2x.png" >/dev/null
done
iconutil -c icns "$work/paper-dive.iconset" -o "$APP/Contents/Resources/paper-dive.icns"

# ------------------------------------------------------------------- plist

cat >"$APP/Contents/Info.plist" <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>paper-dive</string>
  <key>CFBundleDisplayName</key><string>paper-dive</string>
  <key>CFBundleIdentifier</key><string>com.pierrelux.paper-dive</string>
  <key>CFBundleVersion</key><string>0.1.0</string>
  <key>CFBundleShortVersionString</key><string>0.1.0</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleExecutable</key><string>paper-dive</string>
  <key>CFBundleIconFile</key><string>paper-dive</string>
  <key>LSMinimumSystemVersion</key><string>12.0</string>
  <key>NSHighResolutionCapable</key><true/>
</dict>
</plist>
PLIST

# ---------------------------------------------------------------- launcher

cat >"$APP/Contents/MacOS/paper-dive" <<LAUNCHER
#!/bin/bash
# Generated by scripts/make_app.sh — rebuild after moving the checkout.
REPO="$REPO"
LAUNCHER

cat >>"$APP/Contents/MacOS/paper-dive" <<'LAUNCHER'
set -u

PORT="${PAPER_DIVE_PORT:-8765}"
URL="http://127.0.0.1:${PORT}/"
LOG="$HOME/Library/Logs/paper-dive.log"
PROFILE="$HOME/Library/Application Support/paper-dive/browser"
CHROME="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"

die() {
  osascript -e "display alert \"paper-dive\" message \"$1\" as critical" >/dev/null 2>&1
  exit 1
}

listening() { /usr/bin/nc -z 127.0.0.1 "$PORT" >/dev/null 2>&1; }

[ -x "$REPO/.venv/bin/python" ] ||
  die "No virtualenv at $REPO/.venv. Run: uv venv && uv pip install -e ."

# Whoever starts the server owns it; a second launch just opens another window.
owner=0
server=""
browser=""

if ! listening; then
  mkdir -p "$(dirname "$LOG")"
  { echo; echo "=== $(date) ==="; } >>"$LOG"
  ( cd "$REPO" && exec .venv/bin/python -m server.app ) >>"$LOG" 2>&1 &
  server=$!
  owner=1
  for _ in $(seq 1 80); do
    listening && break
    kill -0 "$server" 2>/dev/null || die "The server exited on startup. See $LOG"
    sleep 0.15
  done
  listening || die "The server did not come up within 12s. See $LOG"
fi

cleanup() {
  [ "$owner" = 1 ] || return 0
  [ -n "$browser" ] && kill "$browser" 2>/dev/null
  [ -n "$server" ] && kill "$server" 2>/dev/null
  return 0
}
trap cleanup EXIT INT TERM

if [ -n "${PAPER_DIVE_NO_WINDOW:-}" ]; then
  [ "$owner" = 1 ] && wait "$server"
  exit 0
fi

if [ -x "$CHROME" ]; then
  # A dedicated profile keeps this out of the way of your everyday Chrome and
  # gives a plain window with no tab strip or address bar.
  mkdir -p "$PROFILE"
  "$CHROME" --app="$URL" --user-data-dir="$PROFILE" \
    --no-first-run --no-default-browser-check --window-size=1500,950 \
    >/dev/null 2>&1 &
  browser=$!
else
  open "$URL"
fi

# Hold the app open while the window is: closing it tears the server down.
if [ "$owner" = 1 ]; then
  if [ -n "$browser" ]; then wait "$browser"; else wait "$server"; fi
fi
LAUNCHER

chmod +x "$APP/Contents/MacOS/paper-dive"
touch "$APP"

echo "Done. Open it once, then keep it: right-click its Dock icon > Options > Keep in Dock."
echo "  open '$APP'"
