#!/bin/bash
# Build "paper-dive.app" — a Dock-launchable wrapper around the local server.
#
#   ./scripts/make_app.sh              -> ~/Applications/paper-dive.app
#   DEST=/Applications ./scripts/make_app.sh
#
# The app owns the server: launching it starts uvicorn and opens a window;
# closing the window (or quitting the app) shuts the server down again.

set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEST="${DEST:-$HOME/Applications}"
APP="$DEST/paper-dive.app"

if [ ! -x "$REPO/.venv/bin/python" ]; then
  echo "No virtualenv at $REPO/.venv — run:  uv venv && uv pip install -e ." >&2
  exit 1
fi

echo "Building $APP"
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

# ---------------------------------------------------------------------- icon

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT
python3 "$REPO/scripts/make_icon.py" "$work/icon.png"

mkdir -p "$work/paper-dive.iconset"
for size in 16 32 128 256 512; do
  sips -Z "$size" "$work/icon.png" --out "$work/paper-dive.iconset/icon_${size}x${size}.png" >/dev/null
  sips -Z "$((size * 2))" "$work/icon.png" \
    --out "$work/paper-dive.iconset/icon_${size}x${size}@2x.png" >/dev/null
done
iconutil -c icns "$work/paper-dive.iconset" -o "$APP/Contents/Resources/paper-dive.icns"

# ------------------------------------------------------------------- plist

cat >"$APP/Contents/Info.plist" <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>paper-dive</string>
  <key>CFBundleDisplayName</key><string>paper-dive</string>
  <key>CFBundleIdentifier</key><string>com.pierrelux.paper-dive</string>
  <key>CFBundleVersion</key><string>0.1.0</string>
  <key>CFBundleShortVersionString</key><string>0.1.0</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleExecutable</key><string>paper-dive</string>
  <key>CFBundleIconFile</key><string>paper-dive</string>
  <key>LSMinimumSystemVersion</key><string>12.0</string>
  <key>NSHighResolutionCapable</key><true/>
</dict>
</plist>
PLIST

# ---------------------------------------------------------------- launcher

cat >"$APP/Contents/MacOS/paper-dive" <<LAUNCHER
#!/bin/bash
# Generated by scripts/make_app.sh — rebuild after moving the checkout.
REPO="$REPO"
LAUNCHER

cat >>"$APP/Contents/MacOS/paper-dive" <<'LAUNCHER'
set -u

LOG="$HOME/Library/Logs/paper-dive.log"

die() {
  osascript -e "display alert \"paper-dive\" message \"$1\" as critical" >/dev/null 2>&1
  exit 1
}

[ -x "$REPO/.venv/bin/python" ] ||
  die "No virtualenv at $REPO/.venv. Run: uv venv && uv pip install -e '.[desktop]'"

"$REPO/.venv/bin/python" -c 'import webview' 2>/dev/null ||
  die "The native window needs pywebview. Run: uv pip install -e '.[desktop]'"

mkdir -p "$(dirname "$LOG")"
{ echo; echo "=== $(date) ==="; } >>"$LOG"

cd "$REPO" || die "Cannot reach $REPO"

# exec, so this process (the bundle's main process) becomes the window's
# process and the Dock shows paper-dive rather than a browser or Python.
exec .venv/bin/python -m server.desktop >>"$LOG" 2>&1
LAUNCHER

chmod +x "$APP/Contents/MacOS/paper-dive"
touch "$APP"

echo "Done. Open it once, then keep it: right-click its Dock icon > Options > Keep in Dock."
echo "  open '$APP'"
